spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Caroline93*
    tomcat:
      test-while-idle: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql