spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gotcbtdb
    username: root
    password: Caroline93*
    platform: mysql
    tomcat:
      test-while-idle: true
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false

